version: '3'

networks:
  SUMS-System-Network:
    ipam:
      config:
        - subnet: 163.40.0.0/16

services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - /docker-registry/data:/var/lib/registry
      - ./DockerRegistry/config.yml:/etc/docker/registry/config.yml
    networks:
      SUMS-System-Network:
          ipv4_address: 163.40.0.5
  