version: '3'

networks:
  SUMS-System-Network:
    ipam:
      config:
        - subnet: 163.40.0.0/16

services:
  registry:
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - ./docker-registry/data:/var/lib/registry
      - ./DockerRegistry/config.yml:/etc/docker/registry/config.yml
    networks:
      SUMS-System-Network:
          ipv4_address: 163.40.0.5
  agent-service:
    image: registry.digitalocean.com/vehicle-plus/sums-agent:latest
    restart: always
    command: bash -c "dotnet SUMS-Agent.dll"
    volumes:
      - ./appsettings.json:/app/appsettings.json
    networks:
      SUMS-System-Network:
        ipv4_address: 163.40.0.10
    ports:
      - 6150:80
  database-service:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /home/postgres/admin-database/:/var/lib/postgresql/data
    ports:
      - 5445:5432
    networks:
      SUMS-System-Network:
        ipv4_address: 163.40.0.15
  admin-console:
    image: registry.digitalocean.com/vehicle-plus/admin-console:latest
    restart: always
    command: bash -c "dotnet Admin-Console.dll"
    volumes:
      - ./adminSettings.json:/app/appsettings.json
    networks:
      SUMS-System-Network:
        ipv4_address: 163.40.0.20
    ports:
      - 6250:5000