version: 0.1
log:
  accesslog:
    disabled: true
  level: debug
  formatter: text
  fields:
    service: registry
    environment: staging
http:
  addr: 0.0.0.0:5000
hooks:
  - type: mail
    levels:
      - panic
    options:
      smtp:
        addr: smtp.gmail.com:465
        username: valeo.vehicleplus@gmail.com
        password: cmiwwbklrshesjro
        insecure: true
      from: valeo.vehicleplus@gmail.com
      to:
        - moustafawahdan55@gmail.com
storage:
  filesystem:
    rootdirectory: /var/lib/registry
notifications:
  events:
    includereferences: true
  endpoints:
    - name: alistener
      disabled: false
      url: http://163.30.0.10/WebHook
      timeout: 1s
      threshold: 10
      backoff: 1s