version: 0.1
log:
  accesslog:
    disabled: true
  level: debug
  formatter: text
  fields:
    service: registry
    environment: staging
http:
  addr: 0.0.0.0:5000
hooks:
  - type: mail
    levels:
      - panic
    options:
      smtp:
        addr: smtp.gmail.com:465
        username: valeo.vehicleplus@gmail.com
        password: cmiwwbklrshesjro
        insecure: true
      from: valeo.vehicleplus@gmail.com
      to:
        - moustafawahdan55@gmail.com
storage:
  filesystem:
    rootdirectory: /var/lib/registry
maintenance:
  uploadpurging:
    enabled: true
    age: 168h
    interval: 24h
    dryrun: false
  readonly:
    enabled: false
notifications:
  events:
    includereferences: true
    headers:
        Authorization: [Basic VmVoaWNsZXBsdXMuY2xvdWQ6UEBzc3cwcmQxMjM=]
  endpoints:
    - name: alistener
      disabled: false
      url: https://vehicleplus.cloud/OTA
      timeout: 10s
      threshold: 10
      backoff: 1s